[package]
authors = ["Bastien Dejean <nihilhill@gmail.com>"]
name = "fdb"
version = "0.6.3"
edition = "2018"

[dependencies]
bincode = "1.1.4"
failure = "0.1.5"
getopts = "0.2.19"
regex = "1.1.6"
serde = "1.0.91"
serde_derive = "1.0.91"
time = "0.1.42"
dirs = "1.0.5"
